### ISSUE TITLE
Templates do not apply correctly

### ISSUE THREAD

**Issue by askeron** [bleeptrack/rc3-generator#4]
While the templates are correct previewed, if you click on any template the result is different (see screenshot).

I assume an off-by-one-error. Maybe in the `templatePixels`-function it needs to be `pixels.children[idx+1]` instead of `pixels.children[idx]` from a quick look. I would make a pull request, but paper.js cannot be installed on Windows, so I cannot test anything.

![image](https://user-images.githubusercontent.com/6424268/102808315-70c9fe80-43c0-11eb-9878-e3c249a0854a.png)

**Comment by askeron** [comment]
Ok, it pretty obviously now, that this is the right fix. The bug was introduced through the recent commit 9968f6c7dd8a739e46315d089e6b7a1c752a0d43.

**Comment by bleeptrack** [comment]
Oh yes, good catch! Thanks for noticing! Should be fixed with f0ed549
(btw paper should run on all platforms. In case windows makes trouble, let me know and I can try to help :) )
